### ISSUE TITLE
Failed to compile with boost 1.85.0: missing boost/filesystem/convenience.hpp

### ISSUE THREAD

**Issue by Joey-Xue** [cmbi/xssp#135]
I downloaded hssp3.1.5 and had boost 1.85.0 installed
At first it asked for c++11 and I changed the flag in makefile to -std=c++14
Here's my command and output
```
make install
make  install-am
make[1]: Entering directory '/ictstr01/home/itg/z.xue/hssp-3.1.5'
depbase=`echo src/hssp-nt.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I.  -std=c++14 -pedantic -Wall -Werror -Wno-reorder -pthread -I/home/itg/z.xue/boost/include   -I./src/   -g -O2 -MT src/hssp-nt.o -MD -MP -MF $depbase.Tpo -c -o src/hssp-nt.o src/hssp-nt.cpp &&\
mv -f $depbase.Tpo $depbase.Po
src/hssp-nt.cpp:16:10: fatal error: boost/filesystem/convenience.hpp: No such file or directory
 #include <boost/filesystem/convenience.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:660: src/hssp-nt.o] Error 1
make[1]: Leaving directory '/ictstr01/home/itg/z.xue/hssp-3.1.5'
make: *** [Makefile:909: install] Error 2
```
I do have a filesystem in boost/include, but not sure what's the convenience.hpp file it's asking for, should I downgrade boost to an older version? Which version would you suggest?
Any help and advice is sincerely appreciated.

**Comment by cbaakman** [comment]
The latest boost version that was known to work is 1.78.0
Try that one.

**Comment by Joey-Xue** [comment]
Thanks! The installation was successful!
