### ISSUE TITLE
Compilation fails on cmbi4

### ISSUE THREAD

**Issue by jonblack** [cmbi/xssp#41]
Compilation fails on cmbi4, which is running ubuntu 12.04 LTS. There are multiple reasons:
1. The version of autoconf is too old to parse the configure.ac script. It also fails to check the required version properly;
2. The version of boost is 1.48 and the repository doesn't contain 1.54; however, it does compile with 1.48 after fixing the other problems;
3. The version of gcc doesn't support `std=c++11`; however, it does support `std=c++0x`;
4. Compilation errors due to warnings (strangely these only appear on cmbi4).
